#cloud-config
package_update: true
package_upgrade: true

apt:
  sources:
    docker.list:
      source: deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-compose-plugin
  - git

groups:
  - docker

users:
  - default
  - name: qrtt1
    groups: [docker]

runcmd:
  - systemctl enable docker
  - systemctl start docker
  - |
    sudo -u qrtt1 git clone https://github.com/qtysdk/openvas-lab.git /home/qrtt1/openvas-lab