#cloud-config
package_update: true
package_upgrade: true
apt:
  sources:
    docker.list:
      source: deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
  packages:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose-plugin
    - git
    - nginx-extras
groups:
  - docker
users:
  - default
  - name: qrtt1
    groups:
      - docker
    shell: /usr/bin/bash
write_files:
  - path: /etc/nginx/sites-enabled/proxy.conf
    content: |
      server {
        listen 80;
        server_name qqgvm.qrtt1.io;
        location / {
          proxy_pass http://127.0.0.1:9392;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
      }
runcmd:
  - systemctl enable docker
  - systemctl start docker
  - usermod -u qrtt1 -aG docker qrtt1
  - |
    sudo sh -c 'echo "alias g=git" >> /home/qrtt1/.bashrc'
    sudo -u qrtt1 git config --global user.name "cloud-lab"
    sudo -u qrtt1 git config --global user.email "cloud-lab@qrtt1.io"
    sudo -u qrtt1 git clone https://github.com/qtysdk/openvas-lab.git /home/qrtt1/openvas-lab
  - systemctl reload nginx
